.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. ocean_qt test_ocean_qt
clean: FORCE
	$(MAKE) -C .. ocean_qt_clean test_ocean_qt_clean
check: FORCE
	$(MAKE) -C .. test_ocean_qt_check
ocean-qt ocean-qt.exe: FORCE
	 $(MAKE) -C .. ocean_qt
